# Site settings
title: Caleb Fackler, PharmD, MBA
email: cafackl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
"insert desc here"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://calebfackler.com" # the base hostname & protocol for your site
twitter_username: facksoflife
github_username:  cafackl93

# Build settings
markdown: kramdown
